// Auto-generated from src/lib/currencies.ts — keep in sync with the web app.
// The canonical currency list (code, name, symbol, country).

class Currency {
  final String code;
  final String name;
  final String symbol;
  final String country;
  const Currency(this.code, this.name, this.symbol, this.country);

  String get label => '$code — $name';
}

const List<Currency> kCurrencies = [
  Currency('AED', 'UAE Dirham', 'د.إ', 'United Arab Emirates'),
  Currency('AFN', 'Afghan Afghani', '؋', 'Afghanistan'),
  Currency('ALL', 'Albanian Lek', 'L', 'Albania'),
  Currency('AMD', 'Armenian Dram', '֏', 'Armenia'),
  Currency('ANG', 'Netherlands Antillean Guilder', 'ƒ', 'Netherlands Antilles'),
  Currency('AOA', 'Angolan Kwanza', 'Kz', 'Angola'),
  Currency('ARS', 'Argentine Peso', '\$', 'Argentina'),
  Currency('AUD', 'Australian Dollar', 'A\$', 'Australia'),
  Currency('AWG', 'Aruban Florin', 'ƒ', 'Aruba'),
  Currency('AZN', 'Azerbaijani Manat', '₼', 'Azerbaijan'),
  Currency('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 'Bosnia and Herzegovina'),
  Currency('BBD', 'Barbadian Dollar', 'Bds\$', 'Barbados'),
  Currency('BDT', 'Bangladeshi Taka', '৳', 'Bangladesh'),
  Currency('BGN', 'Bulgarian Lev', 'лв', 'Bulgaria'),
  Currency('BHD', 'Bahraini Dinar', '.د.ب', 'Bahrain'),
  Currency('BIF', 'Burundian Franc', 'Fr', 'Burundi'),
  Currency('BMD', 'Bermudian Dollar', '\$', 'Bermuda'),
  Currency('BND', 'Brunei Dollar', 'B\$', 'Brunei'),
  Currency('BOB', 'Bolivian Boliviano', 'Bs.', 'Bolivia'),
  Currency('BRL', 'Brazilian Real', 'R\$', 'Brazil'),
  Currency('BSD', 'Bahamian Dollar', '\$', 'Bahamas'),
  Currency('BTN', 'Bhutanese Ngultrum', 'Nu', 'Bhutan'),
  Currency('BWP', 'Botswanan Pula', 'P', 'Botswana'),
  Currency('BYN', 'Belarusian Ruble', 'Br', 'Belarus'),
  Currency('BZD', 'Belize Dollar', 'BZ\$', 'Belize'),
  Currency('CAD', 'Canadian Dollar', 'C\$', 'Canada'),
  Currency('CDF', 'Congolese Franc', 'Fr', 'Democratic Republic of the Congo'),
  Currency('CHF', 'Swiss Franc', 'Fr', 'Switzerland'),
  Currency('CLP', 'Chilean Peso', '\$', 'Chile'),
  Currency('CNY', 'Chinese Yuan', '¥', 'China'),
  Currency('COP', 'Colombian Peso', '\$', 'Colombia'),
  Currency('CRC', 'Costa Rican Colón', '₡', 'Costa Rica'),
  Currency('CUP', 'Cuban Peso', '\$', 'Cuba'),
  Currency('CVE', 'Cape Verdean Escudo', '\$', 'Cape Verde'),
  Currency('CZK', 'Czech Koruna', 'Kč', 'Czech Republic'),
  Currency('DJF', 'Djiboutian Franc', 'Fr', 'Djibouti'),
  Currency('DKK', 'Danish Krone', 'kr', 'Denmark'),
  Currency('DOP', 'Dominican Peso', 'RD\$', 'Dominican Republic'),
  Currency('DZD', 'Algerian Dinar', 'د.ج', 'Algeria'),
  Currency('EGP', 'Egyptian Pound', '£', 'Egypt'),
  Currency('ERN', 'Eritrean Nakfa', 'Nfk', 'Eritrea'),
  Currency('ETB', 'Ethiopian Birr', 'Br', 'Ethiopia'),
  Currency('EUR', 'Euro', '€', 'Eurozone'),
  Currency('FJD', 'Fijian Dollar', 'FJ\$', 'Fiji'),
  Currency('FKP', 'Falkland Islands Pound', '£', 'Falkland Islands'),
  Currency('GBP', 'British Pound Sterling', '£', 'United Kingdom'),
  Currency('GEL', 'Georgian Lari', '₾', 'Georgia'),
  Currency('GHS', 'Ghanaian Cedi', '₵', 'Ghana'),
  Currency('GIP', 'Gibraltar Pound', '£', 'Gibraltar'),
  Currency('GMD', 'Gambian Dalasi', 'D', 'Gambia'),
  Currency('GNF', 'Guinean Franc', 'Fr', 'Guinea'),
  Currency('GTQ', 'Guatemalan Quetzal', 'Q', 'Guatemala'),
  Currency('GYD', 'Guyanaese Dollar', '\$', 'Guyana'),
  Currency('HKD', 'Hong Kong Dollar', 'HK\$', 'Hong Kong'),
  Currency('HNL', 'Honduran Lempira', 'L', 'Honduras'),
  Currency('HRK', 'Croatian Kuna', 'kn', 'Croatia'),
  Currency('HTG', 'Haitian Gourde', 'G', 'Haiti'),
  Currency('HUF', 'Hungarian Forint', 'Ft', 'Hungary'),
  Currency('IDR', 'Indonesian Rupiah', 'Rp', 'Indonesia'),
  Currency('ILS', 'Israeli New Shekel', '₪', 'Israel'),
  Currency('INR', 'Indian Rupee', '₹', 'India'),
  Currency('IQD', 'Iraqi Dinar', 'ع.د', 'Iraq'),
  Currency('IRR', 'Iranian Rial', '﷼', 'Iran'),
  Currency('ISK', 'Icelandic Króna', 'kr', 'Iceland'),
  Currency('JMD', 'Jamaican Dollar', 'J\$', 'Jamaica'),
  Currency('JOD', 'Jordanian Dinar', 'د.ا', 'Jordan'),
  Currency('JPY', 'Japanese Yen', '¥', 'Japan'),
  Currency('KES', 'Kenyan Shilling', 'Ksh', 'Kenya'),
  Currency('KGS', 'Kyrgystani Som', 'с', 'Kyrgyzstan'),
  Currency('KHR', 'Cambodian Riel', '៛', 'Cambodia'),
  Currency('KMF', 'Comorian Franc', 'Fr', 'Comoros'),
  Currency('KPW', 'North Korean Won', '₩', 'North Korea'),
  Currency('KRW', 'South Korean Won', '₩', 'South Korea'),
  Currency('KWD', 'Kuwaiti Dinar', 'د.ك', 'Kuwait'),
  Currency('KYD', 'Cayman Islands Dollar', '\$', 'Cayman Islands'),
  Currency('KZT', 'Kazakhstani Tenge', '₸', 'Kazakhstan'),
  Currency('LAK', 'Laotian Kip', '₭', 'Laos'),
  Currency('LBP', 'Lebanese Pound', 'ل.ل', 'Lebanon'),
  Currency('LKR', 'Sri Lankan Rupee', 'Rs', 'Sri Lanka'),
  Currency('LRD', 'Liberian Dollar', '\$', 'Liberia'),
  Currency('LSL', 'Lesotho Loti', 'L', 'Lesotho'),
  Currency('LYD', 'Libyan Dinar', 'ل.د', 'Libya'),
  Currency('MAD', 'Moroccan Dirham', 'د.م.', 'Morocco'),
  Currency('MDL', 'Moldovan Leu', 'L', 'Moldova'),
  Currency('MGA', 'Malagasy Ariary', 'Ar', 'Madagascar'),
  Currency('MKD', 'Macedonian Denar', 'ден', 'North Macedonia'),
  Currency('MMK', 'Myanma Kyat', 'K', 'Myanmar'),
  Currency('MNT', 'Mongolian Tögrög', '₮', 'Mongolia'),
  Currency('MOP', 'Macanese Pataca', 'P', 'Macau'),
  Currency('MRU', 'Mauritanian Ouguiya', 'UM', 'Mauritania'),
  Currency('MUR', 'Mauritian Rupee', 'Rs', 'Mauritius'),
  Currency('MVR', 'Maldivian Rufiyaa', 'Rf', 'Maldives'),
  Currency('MWK', 'Malawian Kwacha', 'MK', 'Malawi'),
  Currency('MXN', 'Mexican Peso', '\$', 'Mexico'),
  Currency('MYR', 'Malaysian Ringgit', 'RM', 'Malaysia'),
  Currency('MZN', 'Mozambican Metical', 'MT', 'Mozambique'),
  Currency('NAD', 'Namibian Dollar', '\$', 'Namibia'),
  Currency('NGN', 'Nigerian Naira', '₦', 'Nigeria'),
  Currency('NIO', 'Nicaraguan Córdoba', 'C\$', 'Nicaragua'),
  Currency('NOK', 'Norwegian Krone', 'kr', 'Norway'),
  Currency('NPR', 'Nepalese Rupee', 'Rs', 'Nepal'),
  Currency('NZD', 'New Zealand Dollar', 'NZ\$', 'New Zealand'),
  Currency('OMR', 'Omani Rial', 'ر.ع.', 'Oman'),
  Currency('PAB', 'Panamanian Balboa', 'B/.', 'Panama'),
  Currency('PEN', 'Peruvian Sol', 'S/', 'Peru'),
  Currency('PGK', 'Papua New Guinean Kina', 'K', 'Papua New Guinea'),
  Currency('PHP', 'Philippine Peso', '₱', 'Philippines'),
  Currency('PKR', 'Pakistani Rupee', 'Rs', 'Pakistan'),
  Currency('PLN', 'Polish Złoty', 'zł', 'Poland'),
  Currency('PYG', 'Paraguayan Guaraní', '₲', 'Paraguay'),
  Currency('QAR', 'Qatari Riyal', 'ر.ق', 'Qatar'),
  Currency('RON', 'Romanian Leu', 'lei', 'Romania'),
  Currency('RSD', 'Serbian Dinar', 'din', 'Serbia'),
  Currency('RUB', 'Russian Ruble', '₽', 'Russia'),
  Currency('RWF', 'Rwandan Franc', 'Fr', 'Rwanda'),
  Currency('SAR', 'Saudi Riyal', 'ر.س', 'Saudi Arabia'),
  Currency('SBD', 'Solomon Islands Dollar', '\$', 'Solomon Islands'),
  Currency('SCR', 'Seychellois Rupee', 'Rs', 'Seychelles'),
  Currency('SDG', 'Sudanese Pound', 'ج.س.', 'Sudan'),
  Currency('SEK', 'Swedish Krona', 'kr', 'Sweden'),
  Currency('SGD', 'Singapore Dollar', 'S\$', 'Singapore'),
  Currency('SHP', 'Saint Helena Pound', '£', 'Saint Helena'),
  Currency('SLL', 'Sierra Leonean Leone', 'Le', 'Sierra Leone'),
  Currency('SOS', 'Somali Shilling', 'Sh', 'Somalia'),
  Currency('SRD', 'Surinamese Dollar', '\$', 'Suriname'),
  Currency('STN', 'São Tomé and Príncipe Dobra', 'Db', 'São Tomé and Príncipe'),
  Currency('SVC', 'Salvadoran Colón', '₡', 'El Salvador'),
  Currency('SYP', 'Syrian Pound', '£', 'Syria'),
  Currency('SZL', 'Swazi Lilangeni', 'L', 'Eswatini'),
  Currency('THB', 'Thai Baht', '฿', 'Thailand'),
  Currency('TJS', 'Tajikistani Somoni', 'SM', 'Tajikistan'),
  Currency('TMT', 'Turkmenistani Manat', 'T', 'Turkmenistan'),
  Currency('TND', 'Tunisian Dinar', 'د.ت', 'Tunisia'),
  Currency('TOP', 'Tongan Paʻanga', 'T\$', 'Tonga'),
  Currency('TRY', 'Turkish Lira', '₺', 'Turkey'),
  Currency('TTD', 'Trinidad and Tobago Dollar', 'TT\$', 'Trinidad and Tobago'),
  Currency('TWD', 'New Taiwan Dollar', 'NT\$', 'Taiwan'),
  Currency('TZS', 'Tanzanian Shilling', 'Sh', 'Tanzania'),
  Currency('UAH', 'Ukrainian Hryvnia', '₴', 'Ukraine'),
  Currency('UGX', 'Ugandan Shilling', 'Sh', 'Uganda'),
  Currency('USD', 'US Dollar', '\$', 'United States'),
  Currency('UYU', 'Uruguayan Peso', '\$U', 'Uruguay'),
  Currency('UZS', 'Uzbekistani Som', 'so\'m', 'Uzbekistan'),
  Currency('VES', 'Venezuelan Bolívar', 'Bs.S', 'Venezuela'),
  Currency('VND', 'Vietnamese Đồng', '₫', 'Vietnam'),
  Currency('VUV', 'Vanuatu Vatu', 'Vt', 'Vanuatu'),
  Currency('WST', 'Samoan Tālā', 'T', 'Samoa'),
  Currency('XAF', 'Central African CFA Franc', 'Fr', 'Central Africa'),
  Currency('XCD', 'East Caribbean Dollar', 'EC\$', 'East Caribbean'),
  Currency('XOF', 'West African CFA Franc', 'Fr', 'West Africa'),
  Currency('XPF', 'CFP Franc', 'Fr', 'French Polynesia'),
  Currency('YER', 'Yemeni Rial', '﷼', 'Yemen'),
  Currency('ZAR', 'South African Rand', 'R', 'South Africa'),
  Currency('ZMW', 'Zambian Kwacha', 'ZK', 'Zambia'),
  Currency('ZWL', 'Zimbabwean Dollar', '\$', 'Zimbabwe'),
];
